const actionTypes = {
	SET_ARRAY: 'SET_ARRAY',
	CHANGE_CURRENT: 'CHANGE_CURRENT',
	CHANGE_CURRENT_TNUMBER: 'CHANGE_CURRENT_TNUMBER',
	TOGGLE_PAUSED: 'TOGGLE_PAUSED',
	SET_PAUSED: 'SET_PAUSED',
	SET_UPCOMING_ARRAY: 'SET_UPCOMING_ARRAY',
	UPCOMING_TO_CURRENT: 'UPCOMING_TO_CURRENT',
}

export default actionTypes;